In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')


In [2]:
# Decision Tree Algorithm 
# Used for both regression and classification
# Can handle categorical features (neumerical) - label encoding
# Feature scaling is not required

In [3]:
# The tree is splitted into branches based on the conditions 
# the ends of the branches that dont split anymore are the cut leaves or decision nodes
# 1st decsion is called the root node

In [4]:
df = pd.read_csv('C:/Users/Palla Anuraag Sharma/Downloads/Datacamp/Datasets/Iris DataSet/Iris.csv')

In [5]:
df = df.set_index('Id')
df.sample(5,random_state=5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id                                                                            
83             5.8           2.7            3.9           1.2  Iris-versicolor
135            6.1           2.6            5.6           1.4   Iris-virginica
115            5.8           2.8            5.1           2.4   Iris-virginica
43             4.4           3.2            1.3           0.2      Iris-setosa
110            7.2           3.6            6.1           2.5   Iris-virginica

In [16]:
from sklearn.preprocessing import LabelEncoder
df['Species_cat'] = LabelEncoder().fit_transform(df.Species)

In [1]:
x = df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y = df['Species_cat']

NameError: name 'df' is not defined

In [19]:
from sklearn.model_selection import train_test_split as tts

x_train,x_test,y_train,y_test = tts(x,y,test_size=0.3,random_state=35)

In [20]:
from sklearn.tree import DecisionTreeClassifier as dtc

d = dtc(random_state=34)

In [22]:
d = d.fit(x_train,y_train)
score = 100 * d.score(x_test,y_test)
print(f"Decision Tree prediction accuracy = {score:4.1f}%")

Decision Tree prediction accuracy = 91.1%


In [24]:
from sklearn.metrics import classification_report, confusion_matrix

# Thre types of Iris in data set
labels = ['Setosa', 'Versicolor', 'Virginica']

# Predict on test data and report scores
y_pred = d.predict(x_test)
print(classification_report(y_test, y_pred, target_names = labels))
print('Primitive Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        16
  Versicolor       0.81      0.93      0.87        14
   Virginica       0.92      0.80      0.86        15

    accuracy                           0.91        45
   macro avg       0.91      0.91      0.91        45
weighted avg       0.92      0.91      0.91        45

Primitive Confusion Matrix:
[[16  0  0]
 [ 0 13  1]
 [ 0  3 12]]


In [30]:
# Call confusion matrix plotting routine
confusion(y_test, y_pred, labels, 'Decision Tree Classification')

NameError: name 'confusion' is not defined