In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
# K NEAREST NEIGHBORS
# Supervised Learning 
# Does not bulid model based on training dataset
# used for Regression and Classification 
# Predict with class or value of the nearest neighbor
# Feature scaling is important
# MEMORY DEMANDING
# Assume the straight line distance to the nearest points and chose the closest one 
# Non Parametric
# Too small k makes noises and has big impact on the prediction

# CLASSIFICATION USING KNN

In [3]:
df = pd.read_csv('C:/Users/Palla Anuraag Sharma/Downloads/Datacamp/Datasets/Iris DataSet/Iris.csv')

In [4]:
df = df.set_index('Id')
df.sample(5,random_state=5)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id                                                                            
83             5.8           2.7            3.9           1.2  Iris-versicolor
135            6.1           2.6            5.6           1.4   Iris-virginica
115            5.8           2.8            5.1           2.4   Iris-virginica
43             4.4           3.2            1.3           0.2      Iris-setosa
110            7.2           3.6            6.1           2.5   Iris-virginica

In [5]:
from sklearn.preprocessing import LabelEncoder
df['Species_cat'] = LabelEncoder().fit_transform(df.Species)

In [6]:
x = df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y = df['Species_cat']

In [7]:
from sklearn.model_selection import train_test_split as tts

x_train,x_test,y_train,y_test = tts(x,y,test_size=0.3,random_state=35)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

knc = KNeighborsClassifier(n_neighbors = 5)
knc.fit(x_train,y_train)
score = 100*knc.score(x_test,y_test)
print(f"KNN 5 neighbors prediction accuracy = {score:5.1f}%")

KNN 5 neighbors prediction accuracy =  95.6%


In [9]:
from sklearn.metrics import classification_report, confusion_matrix

# Predict on test data and report scores
predicted = knc.predict(x_test)
labels = ['Setosa', 'Versicolor', 'Virginica']

print(classification_report(y_test, predicted, target_names = labels))
print(confusion_matrix(y_test, predicted))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        16
  Versicolor       0.93      0.93      0.93        14
   Virginica       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

[[16  0  0]
 [ 0 13  1]
 [ 0  1 14]]


# REGRESSION USING KNN

In [10]:
df = pd.read_csv('C:/Users/Palla Anuraag Sharma/Downloads/Datacamp/Datasets/Tips Dataset/Tips.csv')

In [11]:
df.sample(5,random_state=24)

total_bill   tip     sex smoker   day    time  size
103       22.42  3.48  Female    Yes   Sat  Dinner     2
215       12.90  1.10  Female    Yes   Sat  Dinner     2
144       16.43  2.30  Female     No  Thur   Lunch     2
68        20.23  2.01    Male     No   Sat  Dinner     2
112       38.07  4.00    Male     No   Sun  Dinner     3

In [12]:
# Label encoding using Patsy 
import patsy as pts

In [13]:
y,x = pts.dmatrices('tip ~ total_bill + size + time', data=df, return_type='dataframe')

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state = 29)

In [15]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

knr = KNeighborsRegressor(n_neighbors=5)
knr.fit(x_train,y_train)
y_pred = knr.predict(x_test)

mr2 = r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)

print(f'R^2 Score             = {mr2:5.3f}')
print(f'Mean Squared Error    = {mse:4.2f}')
print(f'Mean Absolute Error   = {mae:4.2f}')

R^2 Score             = -0.088
Mean Squared Error    = 1.49
Mean Absolute Error   = 0.91


In [16]:
from sklearn.preprocessing import MinMaxScaler

# Create and fit scaler
ss = MinMaxScaler().fit(x_train)
x_train_ss = ss.transform(x_train)
x_test_ss = ss.transform(x_test)

y_pred = knr.fit(x_train_ss, y_train).predict(x_test_ss)
mr2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

# Display metrics after scaling features
print(f'R^2 Score             = {mr2:5.3f}')
print(f'Mean Squared Error    = {mse:4.2f}')
print(f'Mean Absolute Error   = {mae:4.2f}')

R^2 Score             = 0.096
Mean Squared Error    = 1.24
Mean Absolute Error   = 0.83
